# Generated by Django 4.1.5 on 2023-01-08 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints_management_system",
            "0003_alter_complaints_complaint_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints",
            name="complaint_status",
            field=models.CharField(
                choices=[
                    ("Settled", "Settled"),
                    ("First Meeting", "First Meeting"),
                    ("Endorsed", "Endorsed"),
                    ("Second Meeting", "Second Meeting"),
                    ("Third Meeting", "Third Meeting"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("Major Complaint", "Major Complaint"),
                    ("Minor Complaint", "Minor Complaint"),
                ],
                default="Minor Complaint",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="date_complaint",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 1, 8, 15, 35, 7, 583799),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="hearing_schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 8, 15, 35, 7, 583781)
            ),
        ),
    ]
